### ISSUE TITLE
Maintaining this repo

### ISSUE THREAD

**Issue by alfie-max** [payrollhero/zoho-subscriptions#2]
Hi @more-ron 

I was hoping if this repo could be revived and added the remaining resources.. 
I just started using this and i see a lot of api's still missing..

**Comment by mathieujobin** [comment]
@alfie-max feel free to open pull-requests

I don't believe @more-ron would be interested working on this

**Comment by mathieujobin** [comment]
@alfie-max just FYI ! 
if you do open pull request, I will review and I might even merge and push gem updates ;)

cheers
